### ISSUE TITLE
Property submission page

### ISSUE THREAD

**Issue by netpoe** [aufacicenta/near.holdings-web#8]
I wonder if we can embrace the power of Wordpress Gutenberg editor (best in the industry) to let users of near.holdings create their Real Estate posts without editing other's posts or accessing other parts of the wordpress CMS.

This is what I'm imagining: 

- A user clicks on "submit property" on the near.holdings site
- The backend creates a wordpress user with a password using the user NEAR wallet address and a fake email, say `address.near@email.com`

http://wp-api.org/node-wpapi/authentication/
http://wp-api.org/node-wpapi/using-the-client/#requesting-different-resources `wp.users().create()`

- the password is reported to the user only once (like when you get PAT tokens on github) 
- they are redirected to the wordpress editor page already logged in to the wordpress site automatically (using oauth)
- they enter a new blank page post type and they can use the editor to submit a new property for approval (some guidelines need to be followed)

https://www.wpbeginner.com/plugins/how-to-allow-editors-to-only-edit-certain-pages-in-wordpress/#:~:text=Simply%20edit%20the%20page%20where,able%20to%20edit%20the%20page.

- Once they create a post, and is approved, we can trigger a webhook to create an NFT of the approved post data (including creating IPFS hashes for the media attached to the post and even ping it using the Crust network)

https://wordpress.com/support/webhooks/

I know this is possible, and not as hard, but we need to make it so that our CMS stays secure. Wordpress is very hackable (we cannot lose the users's funds though, so no big deal)

**Comment by susguzman** [comment]
I find the idea interesting @svpervnder. These properties would be to publish them in the "marketplace" so that later users can buy them with Near?

I think it would be better to have a form, always integrated with Wordpress, and ask for the minimum data. For example: the Owner, location, description and a photo. The idea is to keep it simple for now.

With the issue of security remember that our DB are now public, the only thing that protects us is the password. If we want to change that we must migrate the Next.js part to AWS.
